hydra:
  run:
    dir: results/${image}/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

project: ssi
device: 0
seed: 56
check: False
amp: True

experiment: "2D"
data: "ssi/benchmark/images/generic_2d_all"
image: drosophila

masking_density: 0.01
training_noise: 0.1
lr: 0.001
max_epochs: 3000
patience: 1000

loss: l2
optimizer: esadam
scheduler: plateau  # plateau, cosine

fft_psf: auto  # auto, true, false
clip_before_psf: True
standardize: False  # zero mean, unit variance

two_pass: False  # Use two-pass scheme from Noise2Same
inv_mse_before_forward_model: False  # Calculate invariance mse before forward PSF model
inv_mse_lambda: 2.0  # lambda for the invariance MSE loss